// Auto-generated by codegen - Skygen
// https://cloudflavor.io/projects/skygen
//
// Copyright 2025 Cloudflavor GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::errors::{Error, Result};
use crate::transport::{HttpTransport, Request, Response};
use http::Uri;
use std::sync::Arc;

#[derive(Clone)]
pub struct Client<T: HttpTransport> {
    base: Uri,
    transport: Arc<T>,
}

impl<T: HttpTransport> Client<T> {
    pub fn new(base: Uri, transport: T) -> Self {
        Self {
            base,
            transport: Arc::new(transport),
        }
    }

    pub fn base(&self) -> &Uri {
        &self.base
    }

    pub fn transport(&self) -> &T {
        &self.transport
    }

    /// Join `path_and_query` (starting with '/') to the base URL.
    ///
    /// Example: "/client/v4/zones?per_page=50"
    pub fn join_url(&self, path_and_query: &str) -> Result<Uri> {
        self.base
            .join(path_and_query)
            .map_err(|e| Error::Transport(Box::new(e)))
    }

    pub async fn send(&self, req: Request) -> Result<Response> {
        self.transport.call(req).await
    }
}
