// Auto-generated by codegen - Skygen
// https://cloudflavor.io/projects/skygen
//
// Copyright 2025 Cloudflavor GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::errors::{Error, Result};
use reqwest::redirect::Policy;
use reqwest::{Client as ReqwestClient, ClientBuilder, Request, Response, Url};

#[derive(Clone)]
pub struct Client {
    base: Url,
    inner: ReqwestClient,
}

impl Client {
    /// Build a client pointed at the provider’s default base URL.
    pub fn with_default_transport() -> Result<Self> {
        let base =
            reqwest::Url::parse(crate::API_URL).map_err(|e| Error::Transport(Box::new(e)))?;

        let inner = Self::builder()
            .build()
            .map_err(|e| Error::Transport(Box::new(e)))?;

        Ok(Self { base, inner })
    }

    /// Override the base URL / transport if desired.
    pub fn new(base: reqwest::Url, inner: reqwest::Client) -> Self {
        Self { base, inner }
    }

    pub fn base(&self) -> &Url {
        &self.base
    }

    pub fn builder() -> ClientBuilder {
        ReqwestClient::builder().redirect(Policy::none())
    }

    /// Join `path_and_query` (starting with '/') to the base URL.
    ///
    /// Example: "/client/v4/zones?per_page=50"
    pub fn join_url(&self, path_and_query: &str) -> Result<Url> {
        self.base
            .join(path_and_query)
            .map_err(|e| Error::Transport(Box::new(e)))
    }

    pub async fn send(&self, req: Request) -> Result<Response> {
        #[cfg(feature = "tracing")]
        {
            tracing::debug!(method = %req.method(), url = %req.url(), "sending request");
        }

        let resp = self.inner.execute(req).await?;

        #[cfg(feature = "tracing")]
        {
            tracing::debug!(status = %resp.status(), "received response");
        }

        Ok(resp)
    }
}
