// Auto-generated by codegen - Skygen
// https://cloudflavor.io/projects/skygen
//
// Copyright 2025 Cloudflavor GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug)]
pub enum Error {
    /// Underlying network stack errors (DNS, TLS, timeouts, protocol).
    Transport(Box<dyn std::error::Error + Send + Sync>),

    /// Non-success responses from the API.
    Api(ApiError),

    /// JSON (de)serialization.
    Serialization(serde_json::Error),
}

impl From<serde_json::Error> for Error {
    fn from(e: serde_json::Error) -> Self {
        Self::Serialization(e)
    }
}

impl From<reqwest::Error> for Error {
    fn from(e: reqwest::Error) -> Self {
        Self::Transport(Box::new(e))
    }
}

#[derive(Debug, Clone)]
pub struct ApiError {
    pub status: reqwest::StatusCode,
    pub request_id: Option<String>,
    pub content_type: Option<String>,
    pub body: Vec<u8>,
}

impl std::fmt::Display for ApiError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "status {}", self.status)?;
        if let Some(rid) = &self.request_id {
            write!(f, " request_id={rid}")?;
        }
        Ok(())
    }
}

impl std::error::Error for ApiError {}
